version: "3.8"

services:
  # react_dashboard:
  #   build:
  #     context: ./react_dashboard
  #   command: npm run start
  #   container_name: react_dashboard
  #   restart: unless-stopped
  #   ports:
  #     - "${DASHBOARD_PORT}:${DASHBOARD_PORT}"
  #   environment:
  #     - REACT_APP_MINER_1=${REACT_APP_MINER_1}
  #     - REACT_APP_MINER_2=${REACT_APP_MINER_2}
  #     - REACT_APP_MINER_3=${REACT_APP_MINER_3}
  #   volumes:
  #     - ./react_dashboard:/app
  #     - /app/node_modules

  wallet-server:
    image: goblockchain.azurecr.io/wallet-server:latest
    container_name: wallet-server
    build:
      context: ./wallet_server
    ports:
      - "${WALLET_SERVER_PORT}:${WALLET_SERVER_PORT}"
    environment:
      - WALLET_SERVER_GATEWAY_TO_BLOCKCHAIN=${WALLET_SERVER_GATEWAY_TO_BLOCKCHAIN}
      - WALLET_SERVER_PORT=${WALLET_SERVER_PORT}
      - COMMAND=air
    volumes:
      - ./wallet_server:/app
      - ./block:/app/block
      - ./utils:/app/utils
      - ./wallet:/app/wallet
      - ./go.mod:/app/go.mod:ro
      - ./go.sum:/app/go.sum:ro

  miner-1:
    image: goblockchain.azurecr.io/miner-1:latest
    container_name: miner-1
    build:
      context: ./blockchain_server
    ports:
      - "${MINER_1_PORT}:${MINER_1_PORT}"
    environment:
      - PORT=${MINER_1_PORT}
      - COMMAND=air
    volumes:
      - ./blockchain_server:/app
      - ./block:/app/block
      - ./utils:/app/utils
      - ./wallet:/app/wallet
      - ./go.mod:/app/go.mod:ro
      - ./go.sum:/app/go.sum:ro

  miner-2:
    image: goblockchain.azurecr.io/miner-2:latest
    container_name: miner-2
    build:
      context: ./blockchain_server
    ports:
      - "${MINER_2_PORT}:${MINER_2_PORT}"
    environment:
      - BLOCKCHAIN_SERVER_PORT=${MINER_2_PORT}
      - COMMAND=air
    volumes:
      - ./blockchain_server:/app
      - ./block:/app/block
      - ./utils:/app/utils
      - ./wallet:/app/wallet
      - ./go.mod:/app/go.mod:ro
      - ./go.sum:/app/go.sum:ro

  miner-3:
    image: goblockchain.azurecr.io/miner-3:latest
    container_name: miner-3
    build:
      context: ./blockchain_server
    ports:
      - "${MINER_3_PORT}:${MINER_3_PORT}"
    environment:
      - BLOCKCHAIN_SERVER_PORT=${MINER_3_PORT}
      - COMMAND=air
    volumes:
      - ./blockchain_server:/app
      - ./block:/app/block
      - ./utils:/app/utils
      - ./wallet:/app/wallet
      - ./go.mod:/app/go.mod:ro
      - ./go.sum:/app/go.sum:ro
