version: "3.8"

services:
  react-dashboard:
    build:
      context: ./react_dashboard
    command: npm run start-react
    container_name: react-dashboard
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - REACT_APP_GATEWAY_API_URL=http://localhost:${WALLET_SERVER_PORT}
    volumes:
      - ./react_dashboard:/app
      - /app/node_modules

  wallet-server:
    image: goblockchain.azurecr.io/wallet-server:latest
    container_name: wallet-server
    build:
      context: .
      dockerfile: ./wallet_server/Dockerfile
    ports:
      - ${WALLET_SERVER_PORT}:${WALLET_SERVER_PORT}
    environment:
      - COMMAND=air
      - PORT=${WALLET_SERVER_PORT}
    volumes:
      - .:/app
    restart: unless-stopped

  miner-1:
    image: goblockchain.azurecr.io/miner:latest
    build:
      context: .
      dockerfile: ./blockchain_server/Dockerfile
    ports:
      - 5001:5001
    environment:
      - COMMAND=air
      - PORT=5001
    volumes:
      - .:/app
    restart: unless-stopped

  miner-2:
    image: goblockchain.azurecr.io/miner:latest
    build:
      context: .
      dockerfile: ./blockchain_server/Dockerfile
    container_name: miner-2
    ports:
      - 5002:5002
    environment:
      - COMMAND=air
      - PORT=5002
    volumes:
      - .:/app
    restart: unless-stopped

  miner-3:
    image: goblockchain.azurecr.io/miner:latest
    build:
      context: .
      dockerfile: ./blockchain_server/Dockerfile
    container_name: miner-3
    ports:
      - 5003:5003
    environment:
      - COMMAND=air
      - PORT=5003
    volumes:
      - .:/app
    restart: unless-stopped
