version: "3.8"

services:
  # react_dashboard:
  #   build:
  #     context: ./react_dashboard
  #   command: npm run start
  #   container_name: react_dashboard
  #   restart: unless-stopped
  #   ports:
  #     - "${DASHBOARD_PORT}:${DASHBOARD_PORT}"
  #   environment:
  #     - REACT_APP_MINER_1=${REACT_APP_MINER_1}
  #     - REACT_APP_MINER_2=${REACT_APP_MINER_2}
  #     - REACT_APP_MINER_3=${REACT_APP_MINER_3}
  #   volumes:
  #     - ./react_dashboard:/app
  #     - /app/node_modules

  wallet-server:
    image: goblockchain.azurecr.io/wallet-server:latest
    container_name: wallet-server
    build:
      context: .
      dockerfile: ./wallet_server/Dockerfile
    ports:
      - "${WALLET_SERVER_PORT}:${WALLET_SERVER_PORT}"
    environment:
      - WALLET_SERVER_GATEWAY_TO_BLOCKCHAIN=${WALLET_SERVER_GATEWAY_TO_BLOCKCHAIN}
      - WALLET_SERVER_PORT=${WALLET_SERVER_PORT}
      - COMMAND=air
    volumes:
      - .:/app
    restart: unless-stopped

  # common_miner:
  #   build:
  #     context: ./blockchain_server
  #     dockerfile: ./blockchain_server/Dockerfile
  #   environment:
  #     - COMMAND=air
  #   volumes:
  #     - ./blockchain_server:/app
  #     - ./block:/app/block
  #     - ./utils:/app/utils
  #     - ./wallet:/app/wallet
  #     - ./go.mod:/app/go.mod:ro
  #     - ./go.sum:/app/go.sum:ro
  #   restart: unless-stopped

  # miner-1:
  #   # image: goblockchain.azurecr.io/miner-1
  #   container_name: miner-1
  #   build:
  #     context: ./blockchain_server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${MINER_1_PORT}:${MINER_1_PORT}"
  #   environment:
  #     - BLOCKCHAIN_SERVER_PORT=${MINER_1_PORT}
  #   depends_on:
  #     - common_miner
  #   restart: unless-stopped

  # miner-2:
  #   # image: goblockchain.azurecr.io/miner-2
  #   container_name: miner-2
  #   build:
  #     context: ./blockchain_server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${MINER_2_PORT}:${MINER_2_PORT}"
  #   environment:
  #     - BLOCKCHAIN_SERVER_PORT=${MINER_2_PORT}
  #   depends_on:
  #     - common_miner
  #   restart: unless-stopped

  # miner-3:
  #   # image: goblockchain.azurecr.io/miner-3
  #   container_name: miner-3
  #   build:
  #     context: ./blockchain_server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${MINER_3_PORT}:${MINER_3_PORT}"
  #   environment:
  #     - BLOCKCHAIN_SERVER_PORT=${MINER_3_PORT}
  #   depends_on:
  #     - common_miner
  #   restart: unless-stopped
