version: "3.8"

services:
  react_dashboard:
    build:
      context: ./react_dashboard
    command: npm run start
    container_name: react_dashboard
    restart: unless-stopped
    ports:
      - "${DASHBOARD_PORT}:${DASHBOARD_PORT}"
    environment:
      - REACT_APP_MINER_1=${REACT_APP_MINER_1}
      - REACT_APP_MINER_2=${REACT_APP_MINER_2}
      - REACT_APP_MINER_3=${REACT_APP_MINER_3}
    volumes:
      - ./react_dashboard:/app
      - /app/node_modules

  wallet-server:
    image: goblockchain.azurecr.io/wallet-server:latest
    container_name: wallet-server
    build:
      context: .
      dockerfile: ./wallet_server/Dockerfile
    ports:
      - 5000:5000
    environment:
      - WALLET_SERVER_GATEWAY_TO_BLOCKCHAIN=http://miner-2:5002
      - WALLET_SERVER_PORT=5000
      - COMMAND=air
    volumes:
      - .:/app
    restart: unless-stopped

  miner-1:
    image: goblockchain.azurecr.io/miner:latest
    build:
      context: ./blockchain_server
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    environment:
      - COMMAND=air
      - BLOCKCHAIN_SERVER_PORT=5001
    volumes:
      - .:/app
    restart: unless-stopped

  miner-2:
    image: goblockchain.azurecr.io/miner:latest
    container_name: miner-2
    ports:
      - 5002:5002
    environment:
      - COMMAND=air
      - PORT=5002
    volumes:
      - .:/app
    restart: unless-stopped

  miner-3:
    image: goblockchain.azurecr.io/miner:latest
    container_name: miner-3
    ports:
      - 5003:5003
    environment:
      - COMMAND=air
      - PORT=5003
    volumes:
      - .:/app
    restart: unless-stopped
