version: "3.8"

services:
  wallet-server:
    image: goblockchain.azurecr.io/wallet-server:latest
    container_name: wallet-server
    build:
      context: .
      dockerfile: ./cmd/wallet_server/Dockerfile.prod
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - COMMAND=air
      - MINER_HOST=miner-1
    volumes:
      - .:/app
    restart: unless-stopped

  miner-1:
    image: goblockchain.azurecr.io/miner:latest
    container_name: miner-1
    build:
      context: .
      dockerfile: ./cmd/blockchain_server/Dockerfile.prod
    ports:
      - 5001:5001
    environment:
      - COMMAND=air
      - PORT=5001
      - MINER_HOST=miner
    volumes:
      - .:/app
    restart: unless-stopped

  miner-2:
    image: goblockchain.azurecr.io/miner:latest
    container_name: miner-2
    ports:
      - 5002:5002
    environment:
      - COMMAND=air
      - PORT=5002
      - MINER_HOST=miner
    volumes:
      - .:/app
    restart: unless-stopped

  miner-3:
    image: goblockchain.azurecr.io/miner:latest
    container_name: miner-3
    ports:
      - 5003:5003
    environment:
      - COMMAND=air
      - PORT=5003
      - MINER_HOST=miner
    volumes:
      - .:/app
    restart: unless-stopped
