version: "3.8"

services:
  react_dashboard:
    build:
      context: ./react_dashboard
    command: npm run start
    container_name: react_dashboard
    restart: unless-stopped
    ports:
      - "${DASHBOARD_PORT}:${DASHBOARD_PORT}"
    environment:
      - REACT_APP_MINER_1=${REACT_APP_MINER_1}
      - REACT_APP_MINER_2=${REACT_APP_MINER_2}
      - REACT_APP_MINER_3=${REACT_APP_MINER_3}
    volumes:
      - ./react_dashboard:/app
      - /app/node_modules

  wallet-server:
    image: goblockchain.azurecr.io/wallet-server:latest
    container_name: wallet-server
    build:
      context: .
      dockerfile: ./wallet_server/Dockerfile
    ports:
      - "${WALLET_SERVER_PORT}:${WALLET_SERVER_PORT}"
    environment:
      - WALLET_SERVER_GATEWAY_TO_BLOCKCHAIN=${WALLET_SERVER_GATEWAY_TO_BLOCKCHAIN}
      - WALLET_SERVER_PORT=${WALLET_SERVER_PORT}
      - COMMAND=air
    volumes:
      - .:/app
    restart: unless-stopped

  common-miner:
    image: goblockchain.azurecr.io/miner:latest
    build:
      context: ./blockchain_server
      dockerfile: Dockerfile
    environment:
      - COMMAND=air
    volumes:
      - .:/app
    restart: unless-stopped

  miner-1:
    extends: common_miner
    container_name: miner-1
    ports:
      - "${MINER_1_PORT}:${MINER_1_PORT}"
    environment:
      - BLOCKCHAIN_SERVER_PORT=${MINER_1_PORT}

  miner-2:
    extends: common_miner
    container_name: miner-2
    ports:
      - "${MINER_2_PORT}:${MINER_2_PORT}"
    environment:
      - BLOCKCHAIN_SERVER_PORT=${MINER_2_PORT}

  miner-3:
    extends: common_miner
    container_name: miner-3
    ports:
      - "${MINER_3_PORT}:${MINER_3_PORT}"
    environment:
      - BLOCKCHAIN_SERVER_PORT=${MINER_3_PORT}
