# Start from a base image with Nginx
FROM nginx:alpine

# Copy the static build directory to Nginx's serve directory
COPY build /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx when the container has provisioned
CMD ["nginx", "-g", "daemon off;"]
