apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-dashboard
  template:
    metadata:
      labels:
        app: react-dashboard
    spec:
      containers:
        - name: react-dashboard
          image: elarsaks/react-dashboard:v1.0.2
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_GATEWAY_API_URL
              value: "http://wallet-server:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: react-dashboard-service
spec:
  selector:
    app: react-dashboard
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-server
  template:
    metadata:
      labels:
        app: wallet-server
    spec:
      containers:
        - name: wallet-server
          image: elarsaks/wallet_server:v1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: COMMAND
              value: "air"
            - name: MINER_HOST
              value: "miner-1"
---
apiVersion: v1
kind: Service
metadata:
  name: wallet-server-service
spec:
  selector:
    app: wallet-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain-server
  template:
    metadata:
      labels:
        app: blockchain-server
    spec:
      containers:
        - name: blockchain-server
          image: elarsaks/blockchain_server:v1.0.1
          ports:
            - containerPort: 5001
          env:
            - name: COMMAND
              value: "air"
            - name: BLOCKCHAIN_SERVER_PORT
              value: "5001"
            - name: MINER_HOST
              value: "miner"
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-server-service
spec:
  selector:
    app: blockchain-server
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: NodePort
