root = "."
tmp_dir = "tmp"

[build]
  # Build binary.
  cmd = "go build -o ./tmp/app/engine main.go blockchain_server.go"
  # Read binary.
  bin = "tmp/app"
  # Run binary.
  full_bin = "./tmp/app/engine -port ${PORT}"
  # Watch changes in those files
  include_ext = [ "go", "yml"]
  # Ignore changes in these files
  exclude_dir = ["tmp"]
  # Stop builds from triggering too fast
  delay = 1000 # ms

[misc]
  clean_on_exit = true
