name: Deploy Docker Compose

on:
  push:
    branches:
      - deploy-back-end

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: "2.14.2"

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Docker images
        env:
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
          ACR_REPOSITORY_NAME: GoBlockchain
        run: |
          docker-compose build wallet-server miner-1 miner-2 miner-3
          docker-compose push wallet-server miner-1 miner-2 miner-3

      - name: Deploy to Azure Container Instances
        uses: "azure/aci-deploy@v1"
        with:
          name: GoBlockchain
          resource-group: Go_Blockchain
          location: Sweden Central
          dns-name-label: Go-Blockchain
          ports: |
            5000:5000
            5001:5001
            5002:5002
            5003:5003
          image: ${{ secrets.ACR_LOGIN_SERVER }}/GoBlockchain
          registry-login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          registry-username: ${{ secrets.ACR_USERNAME }}
          registry-password: ${{ secrets.ACR_PASSWORD }}
          cpu: 1
          ip-address: Public
          memory: 1.5
          os-type: Linux
          protocol: TCP
          restart-policy: Always
